// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE_LILc8OVGwlLwXkLGLcSfupx89KHo-8',
    appId: '1:182851291648:web:5613dcd0cdb4a41aa426e5',
    messagingSenderId: '182851291648',
    projectId: 'hoohacks2024-62aa0',
    authDomain: 'hoohacks2024-62aa0.firebaseapp.com',
    storageBucket: 'hoohacks2024-62aa0.appspot.com',
    measurementId: 'G-V1H6N4GHSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqNPGkUzmU7gThV2hwQsYUnhppRWp3cTM',
    appId: '1:182851291648:android:6b9dd1d4e9403f82a426e5',
    messagingSenderId: '182851291648',
    projectId: 'hoohacks2024-62aa0',
    storageBucket: 'hoohacks2024-62aa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpN3ANawl3EXDSjkwCSGYHHsJlcekmLec',
    appId: '1:182851291648:ios:27371635a4046553a426e5',
    messagingSenderId: '182851291648',
    projectId: 'hoohacks2024-62aa0',
    storageBucket: 'hoohacks2024-62aa0.appspot.com',
    iosBundleId: 'com.example.fendFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpN3ANawl3EXDSjkwCSGYHHsJlcekmLec',
    appId: '1:182851291648:ios:e0247fc76beedc55a426e5',
    messagingSenderId: '182851291648',
    projectId: 'hoohacks2024-62aa0',
    storageBucket: 'hoohacks2024-62aa0.appspot.com',
    iosBundleId: 'com.example.fendFlutter.RunnerTests',
  );
}
